### ISSUE TITLE
Jasmine 2.0 compatibility

### ISSUE THREAD

**Issue by theseyi** [codeviking/jasmintd#6]
Is there any chance that this will be upgraded to work with the Jasmine 2.0 api?
2.0 features a new interface for [reporters](https://github.com/pivotal/jasmine/blob/a2a8b5dde234b48f156296b95e9b8c1ba45d1c0c/release_notes/20.md#new-syntax-for-asynchronous-specs)

The current implementation breaks and throws an error since `Jasmine.Reporter` is no longer defined

**Comment by codeviking** [comment]
@theseyi Love it.  

I'm _super_ slammed at work this month.  If you feel inclined to fork, make the revisions you've proposed and submit a patch I'd love to merge it into the core (provided it works).

If you get confused feel free to hit me up here and I'll do my best to help you out.

Thanks!

**Comment by theseyi** [comment]
Sure @codeviking , I can try to work on it in my spare time, busy at work too. Any reason you're wrapping the Block execute method? Probably have to familiarize myself with the Jasmine API by studying the implementation.
EDIT:
Also, if you could provide an overview of what JSTDReporter.js and adapter.js implementations are intended to do so its a bit easier to follow along.

**Comment by codeviking** [comment]
Will do -- I'll get to this tomorrow. Thx!

**Comment by theseyi** [comment]
Looking forward to it thanks.

**Comment by codeviking** [comment]
Hi @theseyi -- I obviously fell off the ball here.

I'm going to have some free dev-time next week and might be able to pull off Jasmine 2.0 compat.  Is this something you'd still be interested in?
